---

- name: install exuberant-ctags for vim
  sudo: yes
  apt: pkg=exuberant-ctags state=present

- name: clone the salt-mines repo to a temp location
  git: >
    repo=git@github.com:technolo-g/salt-mines.git
    dest=/tmp/salt-mines
    accept_hostkey=true
    update=false

- name: run the saltmines setup script
  command: >
    sh /tmp/salt-mines/deploy.sh
    creates=~/.custom_env_created