---

- name: clone the leiningen repo to a temp dir
  git: >
    repo={{ base.lein.repo_url }}
    dest=/tmp/leiningen
    version={{ base.lein.version }}
    update=no

- name: copy the lein binary to /usr/local/sbin
  sudo: true
  command: >
    cp -rp /tmp/leiningen/bin/lein /usr/local/sbin
    creates=/usr/local/sbin/lein
