---

- name: install git
  sudo: true
  apt: pkg=git state=present

- name: install java
  sudo: true
  apt: pkg={{ base.java.package }} state=present

- name: install tree
  sudo: true
  apt: pkg=tree